import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/commons/Navbar";
import Footer from "@/components/commons/Footer";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/provider/auth-provider";
import CartContextProvider from "@/provider/cart-provider";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden max-w-full">
        <AuthProvider>
          <CartContextProvider>
           
        <Navbar/>
        <div className="w-full overflow-x-hidden max-w-full">
         {children}
        
        </div>
       <Toaster position="top-center" richColors/>
       <Footer/>
       </CartContextProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
